export const Questions = [
        { id: 1, text: "¿Qué cosas te ayudan a relajarte cuando estás estresado?" },
        { id: 2, text: "¿Hay algo pequeño o cotidiano que siempre te alegra el día?" },
        { id: 3, text: "¿A qué le tenés miedo y por qué creés que te asusta?" },
        { id: 4, text: "¿Qué es lo que más te gusta de tu forma de ser?" },
        { id: 5, text: "¿Cómo te imaginás dentro de 5, 10 y 25 años?" },
        { id: 6, text: "¿Alguna vez te dijeron que te parecés a alguien famoso? ¿A quién?" },
        { id: 7, text: "¿Qué cualidades sentís que te hacen una buena pareja o alguien fácil de amar?" },
        { id: 8, text: "¿Tenés algún sueño pendiente que todavía te gustaría cumplir?" },
        { id: 9, text: "¿Qué es lo que más necesitás hoy en tu vida?" },
        { id: 10, text: "Pensá en tu año, tu mes y tu semana: decí algo bueno y algo malo de cada uno." },
        { id: 11, text: "¿Cuál fue la peor pesadilla que tuviste... y cuál fue el sueño que más disfrutaste?" },
        { id: 12, text: "¿En qué situaciones te sentís inseguro/a o vulnerable?" },
        { id: 13, text: "¿Qué aspecto de tu vida actual te sorprendería a tu \"yo\" adolescente?" },
        { id: 14, text: "¿Qué cosas venís postergando que te gustaría empezar a hacer hoy mismo?" },
        { id: 15, text: "¿Hay algo de vos que te cueste reconocer o aceptar?" },
        { id: 16, text: "¿Hubo un momento en el que sentiste que estabas usando bien tu tiempo? ¿Cuál fue?" },
        { id: 17, text: "¿Sentís que te convertiste en la persona que querías ser?" },
        { id: 18, text: "¿Qué hacés cuando necesitás liberar emociones intensas?" },
        { id: 19, text: "¿Qué aporte creés que hacés a tu entorno o grupo cercano?" },
        { id: 20, text: "¿Hay algo que a muchos les parezca importante pero a vos no te interese? ¿Por qué?" },
        { id: 21, text: "¿Cómo te das cuenta de que estás enamorado/a de alguien?" },
        { id: 22, text: "¿Perdonaste o perdonarías una infidelidad? ¿Por qué sí o por qué no?" },
        { id: 23, text: "Si pudieras cambiar algo de tu pasado, ¿qué sería?" },
        { id: 24, text: "¿Te enamoraste alguna vez? Si sí, ¿qué recordás de tu primer amor? Si no, ¿qué esperás del amor?" },
        { id: 25, text: "¿Tenés tatuajes? Si sí, contá algo sobre cada uno. Si no, ¿qué te tatuarías si tuvieras que hacerlo sí o sí?" },
        { id: 26, text: "¿Cómo se llama tu papá? Contá una cosa linda, divertida o curiosa sobre él." },
        { id: 27, text: "¿Cómo se llama tu mamá? Contá una cosa linda, divertida o curiosa sobre ella." },
        { id: 28, text: "¿Extrañás a alguien hoy? ¿Qué te detiene de invitarlo/a a juntarse?" },
        { id: 29, text: "¿Recordás algún cumplido que te haya dejado una huella positiva?" },
        { id: 30, text: "¿A quién recurrís cuando estás mal o necesitás contención?" },
        { id: 31, text: "¿Hubo alguien que recientemente te haya hecho sentir bien con vos mismo/a?" },
        { id: 32, text: "¿Qué significa para vos la amistad?" },
        { id: 33, text: "¿Creés que puede existir una amistad real entre un hombre y una mujer?" },
        { id: 34, text: "¿Cuál es tu día favorito del año y por qué?" },
        { id: 35, text: "¿Qué te enamora o te atrae especialmente de una persona?" },
        { id: 36, text: "¿Qué es lo último que pensaste en comprarte?" },
        { id: 37, text: "¿Tenés un número que sentís como tuyo o de la suerte? ¿Por qué?" },
        { id: 38, text: "¿Qué idioma te gustaría hablar y qué harías con esa habilidad?" },
        { id: 39, text: "¿Tocás algún instrumento? Si no, ¿cuál te gustaría aprender y por qué?" },
        { id: 40, text: "¿Conocés algún dato curioso o poco común que te parezca genial?" },
        { id: 41, text: "Nombrá una canción que te guste ahora, una que siempre te haya gustado y una que te haya dejado de gustar." },
        { id: 42, text: "¿Con qué personaje de una película (Disney, DreamWorks, Pixar, etc.) te identificás?" },
        { id: 43, text: "¿Cuál es tu color favorito y qué te transmite?" },
        { id: 44, text: "¿Qué lugar elegirías vos para una primera cita y por qué?" },
        { id: 45, text: "¿Hay alguna flor, planta o árbol que te guste mucho o te inspire algo especial?" },
        { id: 46, text: "¿Cuál es tu comida chatarra preferida sin culpa?" },
        { id: 47, text: "Si tuvieras que armar un cuarto de helado con hasta tres gustos, ¿cuáles elegís?" },
        { id: 48, text: "¿Sabés por qué te pusieron tu nombre y qué significa?" },
        { id: 49, text: "Si pudieras cambiar algo del mundo hoy, ¿qué cambiarías?" },
        { id: 50, text: "¿Qué ideas tenés sobre tu futuro y qué te gustaría que pase?" },
        { id: 51, text: "Si pudieras vivir un día en la vida de otra persona, ¿a quién elegirías y por qué?" },
        { id: 52, text: "¿Qué enseñanza valiosa te dejó alguien que admirás?" },
        { id: 53, text: "¿A quién admirás y qué cualidades valorás en esa persona?" },
        { id: 54, text: "Decí tres cosas por las que estés agradecido en este momento." },
        { id: 55, text: "¿Cómo distinguís lo que está bien de lo que está mal? ¿Tenés una brújula interna?" },
        { id: 56, text: "Si pudieras tener un superpoder, ¿cuál elegirías y para qué lo usarías?" },
        { id: 57, text: "¿Pensás que hay algo después de la muerte? ¿Qué te imaginás?" },
        { id: 58, text: "¿Creés en algún tipo de Dios o fuerza superior? ¿Cómo lo/a describirías?" },
        { id: 59, text: "¿Qué significa para vos ser libre?" },
        { id: 60, text: "¿Creés más en las casualidades o en que todo tiene una causa?" },
        { id: 61, text: "¿Te asusta el paso del tiempo? ¿Por qué?" },
        { id: 62, text: "Si tuvieras que elegir dos personas para acompañarte en una gran aventura, ¿a quiénes elegirías y por qué?" },
        { id: 63, text: "Si encontrás un millón de dólares en la calle, ¿qué es lo primero que hacés?" },
        { id: 64, text: "¿Podrías tener una relación abierta? ¿Qué te haría considerarlo o no?" },
        { id: 65, text: "¿Alguna vez intentaste cambiar a alguien? ¿Qué aprendiste de esa experiencia?" },
        { id: 66, text: "¿Hay algo que te encanta hacer pero sabés que no te sale bien?" },
        { id: 67, text: "¿Hubo algún proyecto o idea que dejaste en pausa o abandonaste?" },
        { id: 68, text: "¿Te arrepentís de algo en tu vida? ¿De qué?" },
        { id: 69, text: "¿Hay algo que hiciste más de lo necesario y te gustaría haber hecho menos?" },
        { id: 70, text: "¿En el juego Carrera de Mente, cuál es tu categoría fuerte y cuál la más floja? (Arte, Ciencia y Tecnología, Historia, Geografía, Espectáculos, Deportes)" },
        { id: 71, text: "¿Cuál sería una buena razón para brindar con champagne?" },
        { id: 72, text: "¿Preferís leer libros o ver series? ¿Por qué?" },
        { id: 73, text: "¿Cuál es tu película favorita y qué te gusta tanto de ella?" },
        { id: 74, text: "¿Recordás un momento en el que sentiste que tuviste mucha suerte?" },
        { id: 75, text: "¿Qué tema te apasiona tanto que podrías hablar horas?" },
        { id: 76, text: "¿Cuál es tu estación favorita del año y qué te gusta de ella?" },
        { id: 77, text: "¿Tenés algún vicio del que no te querés desprender? ¿Cuál?" },
        { id: 78, text: "¿Tenés algún deportista favorito? ¿Qué admirás de esa persona?" },
        { id: 79, text: "¿Tenés una frase o cita que te inspire o te represente?" },
        { id: 80, text: "¿Qué cosas venís postergando que te gustaría empezar a hacer hoy?" },
        { id: 81, text: "Si te dieran un millón de dólares para gastar en 24 horas, ¿qué harías con esa plata?" },
        { id: 82, text: "¿Qué hábito pequeño sentís que cambió tu vida para mejor?" },
        { id: 83, text: "¿Cuál fue la última vez que te sentiste verdaderamente orgulloso/a de vos mismo/a? ¿Qué hiciste?" },
        { id: 84, text: "¿Qué consejo de alguien mayor seguís recordando y por qué?" },
        { id: 85, text: "¿Qué lugar te hace sentir en casa, aunque no vivas ahí?" },
        { id: 86, text: "¿Qué aprendiste sobre vos mismo/a en el último año?" },
        { id: 87, text: "¿Hay alguna decisión difícil que hoy sabés que tomaste bien? ¿Cuál?" },
        { id: 88, text: "¿Tenés alguna rutina o ritual que sea importante para tu bienestar?" },
        { id: 89, text: "¿Conociste a alguien que te dio una buena o mala primera impresión, y después cambiaste de opinión? ¿Qué pasó?" },
        { id: 90, text: "¿Qué cosa de tu infancia todavía te acompaña hoy?" },
        { id: 91, text: "¿Te cuesta decir que no? ¿Por qué creés que te pasa eso?" },
        { id: 92, text: "¿Hay algo que te dé un poco de vergüenza contar pero que sentís que te define?" },
        { id: 93, text: "¿En qué lugares, contextos o grupos te sentís fuera de lugar o incómodo?" },
        { id: 94, text: "¿Hay alguna habilidad o talento tuyo que sentís que los demás no conocen?" },
        { id: 95, text: "¿Te cuesta pedir ayuda? ¿En qué situaciones más lo notás?" },
        { id: 96, text: "¿Qué parte de tu vida te gustaría poder revivir, aunque sea un día?" },
        { id: 97, text: "¿Hay alguna persona con la que ya no hablás y te gustaría volver a conectar?" },
        { id: 98, text: "¿Qué costumbre de tu familia te gusta conservar y cuál no?" },
        { id: 99, text: "¿Te cuesta recibir halagos? ¿Cómo reaccionás cuando te los hacen?" },
        { id: 100, text: "¿Cuál fue la última vez que cambiaste de opinión sobre algo importante? ¿Qué te hizo cambiar?" },
        { id: 101, text: "¿Qué te hubiera gustado aprender antes, pero recién entendiste de grande?" },
        { id: 102, text: "¿Tenés alguna meta que te dé miedo pero también muchas ganas de intentar?" },
        { id: 103, text: "¿Qué cosas hacés para cuidar tu salud mental o emocional?" },
        { id: 104, text: "¿Qué te gustaría que los demás valoren más de vos?" },
        { id: 105, text: "¿Qué creés que los demás asumen de vos, pero no es cierto?" },
        { id: 106, text: "¿Te cuesta cerrar etapas? ¿Hay alguna que todavía no hayas cerrado del todo?" },
        { id: 107, text: "¿Qué parte de tu personalidad te llevó más tiempo aceptar?" },
        { id: 108, text: "¿Hay algo que admirás en alguien y que te gustaría incorporar a tu vida?" },
        { id: 109, text: "¿Cuál fue una pequeña victoria que te hizo sentir grande?" },
        { id: 110, text: "¿Hay algo que estés construyendo en silencio y que todavía no contaste a nadie?" },
        { id: 111, text: "¿Qué te hubiera gustado que alguien te dijera cuando eras más chico/a? ¿Hay algo que sentís que faltó en tu crianza?" },
        { id: 112, text: "¿Qué aprendiste haciendo las cosas mal?" },
        { id: 113, text: "¿Qué pensás que diría tu versión de 10 años atrás si te viera hoy?" }
];
