export const questions = [
        "¿Qué cosas te ayudan a relajarte cuando estás estresado?",
        "¿Hay algo pequeño o cotidiano que siempre te alegra el día?",
        "¿A qué le tenés miedo y por qué creés que te asusta?",
        "¿Qué es lo que más te gusta de tu forma de ser?",
        "¿Cómo te imaginás dentro de 5, 10 y 25 años?",
        "¿Alguna vez te dijeron que te parecés a alguien famoso? ¿A quién?",
        "¿Qué cualidades sentís que te hacen una buena pareja o alguien fácil de amar?",
        "¿Tenés algún sueño pendiente que todavía te gustaría cumplir?",
        "¿Qué es lo que más necesitás hoy en tu vida?",
        "Pensá en tu año, tu mes y tu semana: decí algo bueno y algo malo de cada uno.",
        "¿Cuál fue la peor pesadilla que tuviste... y cuál fue el sueño que más disfrutaste?",
        "¿En qué situaciones te sentís inseguro/a o vulnerable?",
        "¿Qué aspecto de tu vida actual te sorprendería a tu \"yo\" adolescente?",
        "¿Qué cosas venís postergando que te gustaría empezar a hacer hoy mismo?",
        "¿Hay algo de vos que te cueste reconocer o aceptar?",
        "¿Hubo un momento en el que sentiste que estabas usando bien tu tiempo? ¿Cuál fue?",
        "¿Sentís que te convertiste en la persona que querías ser?",
        "¿Qué hacés cuando necesitás liberar emociones intensas?",
        "¿Qué aporte creés que hacés a tu entorno o grupo cercano?",
        "¿Hay algo que a muchos les parezca importante pero a vos no te interese? ¿Por qué?",
        "¿Cómo te das cuenta de que estás enamorado/a de alguien?",
        "¿Perdonaste o perdonarías una infidelidad? ¿Por qué sí o por qué no?",
        "Si pudieras cambiar algo de tu pasado, ¿qué sería?",
        "¿Te enamoraste alguna vez? Si sí, ¿qué recordás de tu primer amor? Si no, ¿qué esperás del amor?",
        "¿Tenés tatuajes? Si sí, contá algo sobre cada uno. Si no, ¿qué te tatuarías si tuvieras que hacerlo sí o sí?",
        "¿Cómo se llama tu papá? Contá una cosa linda, divertida o curiosa sobre él.",
        "¿Cómo se llama tu mamá? Contá una cosa linda, divertida o curiosa sobre ella.",
        "¿Extrañás a alguien hoy? ¿Qué te detiene de invitarlo/a a juntarse?",
        "¿Recordás algún cumplido que te haya dejado una huella positiva?",
        "¿A quién recurrís cuando estás mal o necesitás contención?",
        "¿Hubo alguien que recientemente te haya hecho sentir bien con vos mismo/a?",
        "¿Qué significa para vos la amistad?",
        "¿Creés que puede existir una amistad real entre un hombre y una mujer?",
        "¿Cuál es tu día favorito del año y por qué?",
        "¿Qué te enamora o te atrae especialmente de una persona?",
        "¿Qué es lo último que pensaste en comprarte?",
        "¿Tenés un número que sentís como tuyo o de la suerte? ¿Por qué?",
        "¿Qué idioma te gustaría hablar y qué harías con esa habilidad?",
        "¿Tocás algún instrumento? Si no, ¿cuál te gustaría aprender y por qué?",
        "¿Conocés algún dato curioso o poco común que te parezca genial?",
        "Nombrá una canción que te guste ahora, una que siempre te haya gustado y una que te haya dejado de gustar.",
        "¿Con qué personaje de una película (Disney, DreamWorks, Pixar, etc.) te identificás?",
        "¿Cuál es tu color favorito y qué te transmite?",
        "¿Qué lugar elegirías vos para una primera cita y por qué?",
        "¿Hay alguna flor, planta o árbol que te guste mucho o te inspire algo especial?",
        "¿Cuál es tu comida chatarra preferida sin culpa?",
        "Si tuvieras que armar un cuarto de helado con hasta tres gustos, ¿cuáles elegís?",
        "¿Sabés por qué te pusieron tu nombre y qué significa?",
        "Si pudieras cambiar algo del mundo hoy, ¿qué cambiarías?",
        "¿Qué ideas tenés sobre tu futuro y qué te gustaría que pase?",
        "Si pudieras vivir un día en la vida de otra persona, ¿a quién elegirías y por qué?",
        "¿Qué enseñanza valiosa te dejó alguien que admirás?",
        "¿A quién admirás y qué cualidades valorás en esa persona?",
        "Decí tres cosas por las que estés agradecido en este momento.",
        "¿Cómo distinguís lo que está bien de lo que está mal? ¿Tenés una brújula interna?",
        "Si pudieras tener un superpoder, ¿cuál elegirías y para qué lo usarías?",
        "¿Pensás que hay algo después de la muerte? ¿Qué te imaginás?",
        "¿Creés en algún tipo de Dios o fuerza superior? ¿Cómo lo/a describirías?",
        "¿Qué significa para vos ser libre?",
        "¿Creés más en las casualidades o en que todo tiene una causa?",
        "¿Te asusta el paso del tiempo? ¿Por qué?",
        "Si tuvieras que elegir dos personas para acompañarte en una gran aventura, ¿a quiénes elegirías y por qué?",
        "Si encontrás un millón de dólares en la calle, ¿qué es lo primero que hacés?",
        "¿Podrías tener una relación abierta? ¿Qué te haría considerarlo o no?",
        "¿Alguna vez intentaste cambiar a alguien? ¿Qué aprendiste de esa experiencia?",
        "¿Hay algo que te encanta hacer pero sabés que no te sale bien?",
        "¿Hubo algún proyecto o idea que dejaste en pausa o abandonaste?",
        "¿Te arrepentís de algo en tu vida? ¿De qué?",
        "¿Hay algo que hiciste más de lo necesario y te gustaría haber hecho menos?",
        "¿En el juego Carrera de Mente, cuál es tu categoría fuerte y cuál la más floja? (Arte, Ciencia y Tecnología, Historia, Geografía, Espectáculos, Deportes)",
        "¿Cuál sería una buena razón para brindar con champagne?",
        "¿Preferís leer libros o ver series? ¿Por qué?",
        "¿Cuál es tu película favorita y qué te gusta tanto de ella?",
        "¿Recordás un momento en el que sentiste que tuviste mucha suerte?",
        "¿Qué tema te apasiona tanto que podrías hablar horas?",
        "¿Cuál es tu estación favorita del año y qué te gusta de ella?",
        "¿Tenés algún vicio del que no te querés desprender? ¿Cuál?",
        "¿Tenés algún deportista favorito? ¿Qué admirás de esa persona?",
        "¿Tenés una frase o cita que te inspire o te represente?",
        "¿Qué cosas venís postergando que te gustaría empezar a hacer hoy?",
        "Si te dieran un millón de dólares para gastar en 24 horas, ¿qué harías con esa plata?",
        "¿Qué hábito pequeño sentís que cambió tu vida para mejor?",
        "¿Cuál fue la última vez que te sentiste verdaderamente orgulloso/a de vos mismo/a? ¿Qué hiciste?",
        "¿Qué consejo de alguien mayor seguís recordando y por qué?",
        "¿Qué lugar te hace sentir en casa, aunque no vivas ahí?",
        "¿Qué aprendiste sobre vos mismo/a en el último año?",
        "¿Hay alguna decisión difícil que hoy sabés que tomaste bien? ¿Cuál?",
        "¿Tenés alguna rutina o ritual que sea importante para tu bienestar?",
        "¿Conociste a alguien que te dio una buena o mala primera impresión, y después cambiaste de opinión? ¿Qué pasó?",
        "¿Qué cosa de tu infancia todavía te acompaña hoy?",
        "¿Te cuesta decir que no? ¿Por qué creés que te pasa eso?",
        "¿Hay algo que te dé un poco de vergüenza contar pero que sentís que te define?",
        "¿En qué lugares, contextos o grupos te sentís fuera de lugar o incómodo?",
        "¿Hay alguna habilidad o talento tuyo que sentís que los demás no conocen?",
        "¿Te cuesta pedir ayuda? ¿En qué situaciones más lo notás?",
        "¿Qué parte de tu vida te gustaría poder revivir, aunque sea un día?",
        "¿Hay alguna persona con la que ya no hablás y te gustaría volver a conectar?",
        "¿Qué costumbre de tu familia te gusta conservar y cuál no?",
        "¿Te cuesta recibir halagos? ¿Cómo reaccionás cuando te los hacen?",
        "¿Cuál fue la última vez que cambiaste de opinión sobre algo importante? ¿Qué te hizo cambiar?",
        "¿Qué te hubiera gustado aprender antes, pero recién entendiste de grande?",
        "¿Tenés alguna meta que te dé miedo pero también muchas ganas de intentar?",
        "¿Qué cosas hacés para cuidar tu salud mental o emocional?",
        "¿Qué te gustaría que los demás valoren más de vos?",
        "¿Qué creés que los demás asumen de vos, pero no es cierto?",
        "¿Te cuesta cerrar etapas? ¿Hay alguna que todavía no hayas cerrado del todo?",
        "¿Qué parte de tu personalidad te llevó más tiempo aceptar?",
        "¿Hay algo que admirás en alguien y que te gustaría incorporar a tu vida?",
        "¿Cuál fue una pequeña victoria que te hizo sentir grande?",
        "¿Hay algo que estés construyendo en silencio y que todavía no contaste a nadie?",
        "¿Qué te hubiera gustado que alguien te dijera cuando eras más chico/a? ¿Hay algo que sentís que faltó en tu crianza?",
        "¿Qué aprendiste haciendo las cosas mal?",
        "¿Qué pensás que diría tu versión de 10 años atrás si te viera hoy?"
    ]